services:
  webapplication1:
    image: webapplication1
    build:
      context: .
      dockerfile: WebApplication1/Dockerfile

  ohd:
    image: ohd
    build:
      context: .
      dockerfile: Ohd/Dockerfile

  ohd1:
    image: ohd1
    build:
      context: .
      dockerfile: Ohd1/Dockerfile

